[general]
import = [
"./themes/gruvbox_material_medium_dark.toml"
# "./themes/catppuccin_macchiato.toml",
# "./themes/tokyo_night.toml",
]

[window]
padding = { x = 10, y = 10 }

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
