[general]
import = [
"./themes/gruvbox_material_medium_dark.toml",
]


[font]
# normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
